# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa4b146c99ee071d3e9f7ee7d7bc178208d539584b383a5242f85dbfeb7a693007b575c48878cc3b1c72ce951ea50a184a583663bd951cf5c95c6de6d0ef3c4f

test:
  secret_key_base: 2d2063b1496f3735918db2652a86f2dc30055f8b0db2d4ac0ea6d4a6140eaa6a6b7c1b9d67d201aac1a7f6a00e4f54f90d3422c417529c8ffd842a166e5d7725

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
